name: Renovate
on:
  pull_request:
    branches:
      - main  # Pre-merge validation
  merge_group:
    branches:
      - main  # Merge queue validation

jobs:
  call:
    name: Call
    uses: ./.github/workflows/reusable-renovate.yml
    permissions:
      contents: read
