name: Renovate
on:
  pull_request:
    branches:
      - main  # Pre-merge validation
  merge_group:
    branches:
      - main  # Merge queue validation

jobs:
  config:
    uses: ./.github/workflows/reusable-renovate.yml
    name: Config
    permissions:
      contents: read
