## Reusable GitHub workflow for repositories with Renovate config files.
## Reference: https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows
##

name: Reusable Renovate Workflow
on:
  workflow_call:
    inputs:
      config_files:
        description: >
          A newline-separated list of Renovate configuration files.
          When not provided, all default config file names are checked.
          See https://docs.renovatebot.com/config-validation for more details.
        type: string
        required: false

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        name: Checkout Repository
      - name: Validate Config Files
        shell: bash
        env:
          CONFIG_FILES: ${{ inputs.config_files }}
        run: |
          set -euo pipefail

          # Avoid a slow global install, and npx's cache will speed up repeated runs.
          validate() {
            npx --yes --package renovate -- renovate-config-validator --strict "$@"
          }

          if [[ -z "$CONFIG_FILES" ]]; then
            validate
          else
            # Read CONFIG_FILES line by line
            while IFS= read -r file; do
              # Skip blank lines
              [[ -z "$file" ]] && continue

              validate "$file"
            done <<< "$CONFIG_FILES"
          fi
